# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cpplint:
    name: cpplint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cpplint
          path: ~/.cache/pip

      - name: Pyhton
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: cpplint
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cpplint
          cpplint \
            --repository=. \
            --recursive \
            --filter=-whitespace/line_length,-whitespace/braces,-whitespace/comments,-runtime/indentation_namespace,-whitespace/indent,-readability/braces,-whitespace/newline,-readability/todo,-runtime/int,-build/c++11 \
            src

  arduino:
    name: Arduino
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - core: esp32:esp32
            board: esp32:esp32:esp32
            index_url: https://espressif.github.io/arduino-esp32/package_esp32_index.json
          # - core: esp32:esp32
          #   board: esp32:esp32:esp32
          #   index_url: https://espressif.github.io/arduino-esp32/package_esp32_dev_index.json

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install arduino-cli
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh

      - name: Update core index
        run: arduino-cli core update-index --additional-urls "${{ matrix.index_url }}"

      - name: Install core
        run: arduino-cli core install --additional-urls "${{ matrix.index_url }}" ${{ matrix.core }}

      - name: Install ArduinoJson
        run: arduino-cli lib install ArduinoJson

      - name: Build Callbacks
        run: arduino-cli compile --library . --warnings all -b ${{ matrix.board }} "examples/Callbacks/Callbacks.ino" --build-property build.extra_flags=-DMYCILA_JSON_SUPPORT

      - name: Build Thyristor
        run: arduino-cli compile --library . --warnings all -b ${{ matrix.board }} "examples/Thyristor/Thyristor.ino" --build-property build.extra_flags=-DMYCILA_JSON_SUPPORT

  platformio:
    name: "pio:${{ matrix.env }}:${{ matrix.board }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - env: ci-arduino-3
            board: esp32dev
          - env: ci-arduino-3
            board: esp32-s2-saola-1
          - env: ci-arduino-3
            board: esp32-s3-devkitc-1
          - env: ci-arduino-3
            board: esp32-c3-devkitc-02
          - env: ci-arduino-3
            board: esp32-c6-devkitc-1
          - env: ci-arduino-3
            board: esp32-h2-devkitm-1

          # - env: ci-arduino-rc
          #   board: esp32dev
          # - env: ci-arduino-rc
          #   board: esp32-s2-saola-1
          # - env: ci-arduino-rc
          #   board: esp32-s3-devkitc-1
          # - env: ci-arduino-rc
          #   board: esp32-c3-devkitc-02
          # - env: ci-arduino-rc
          #   board: esp32-c6-devkitc-1
          # - env: ci-arduino-rc
          #   board: esp32-h2-devkitm-1
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pio
          path: |
            ~/.cache/pip
            ~/.platformio

      - name: Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pip install --upgrade intelhex

      - run: PLATFORMIO_SRC_DIR=examples/Callbacks PIO_BOARD=${{ matrix.board }} pio run -e ${{ matrix.env }}
      - run: PLATFORMIO_SRC_DIR=examples/Thyristor PIO_BOARD=${{ matrix.board }} pio run -e ${{ matrix.env }}
